# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgpkg < Formula
  desc "pgpkg makes writing and deploying pl/pgsql functions easy."
  homepage "https://pgpkg.dev/"
  version "0.0.3"
  license "MIT"
  depends_on :macos

  on_intel do
    url "https://github.com/pgpkg/pgpkg/releases/download/0.0.3/pgpkg_Darwin_x86_64.tar.gz"
    sha256 "0aed9fd9abf5130d03a335b0ca4c9076a56c702e7c260fb48756e4a696b1ad2e"

    def install
      bin.install "pgpkg"
    end
  end
  on_arm do
    url "https://github.com/pgpkg/pgpkg/releases/download/0.0.3/pgpkg_Darwin_arm64.tar.gz"
    sha256 "88342960f42d7e98a32b1928c84ed97a65db8d862de031797e7dc5d7928cb661"

    def install
      bin.install "pgpkg"
    end
  end
end
